# Copyright (c) 2021 Tailscale Inc & AUTHORS All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

#FROM ghcr.io/tailscale/tailscale:latest
FROM fuzzylemma/tailscale:v1.22

COPY entrypoint.sh /entrypoint.sh 
CMD [ "/entrypoint.sh" ]

#CMD ["/bin/sh"]
